apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - git::https://github.com/rancher/local-path-provisioner//deploy?ref=v0.0.22

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: local-path-config
    namespace: local-path-storage
    behavior: merge
    files:
      - config.json=config.json
